Implement MVP of Chat Page
cornellh4i/okb-hope pull request #30
Opened 2023-04-19 18:39 UTC by doctakim

## Overview

- Implemented key components consistent with Figma
- Added real time updates from Firebase

## Changes Made

- Chat Page includes real time updates from chats in the firebase db. Messages can be sent and received.

## Test Coverage

- Messages were sent and received to test if they render properly (sent vs. received).

## Next Steps (delete if not applicable)

## Related PRs or Issues (delete if not applicable)

## Screenshots (delete if not applicable)

<! -- This could include of screenshots of the new feature / proof that the changes work. -->
<img width="1512" alt="Screenshot 2023-04-19 at 2 39 14 PM" src="https://user-images.githubusercontent.com/100223126/233169457-842c71cb-acc3-4586-852f-3c8dd8726485.png">

2023-04-21 17:02 UTC, DylanTom commented on backend/firebase/firebase.tsx
Why was `orderBy, limit, DocumentData` included? It was added but never exported or used.

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/assets/chevron_up.tsx
We should standardize how we add `svg` files. Do we want to use `@webpack/svgr` or do it how @doctakim @p-m-ishra did it here? 

@sriramanved I think you should make the final call.

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/components/ChatApp/ChatApp.tsx
> +      // onClick={}
Commented code should be removed from PR unless properly documented as a placeholder.

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/components/ChatApp/ChatArea.tsx
> +      // onClick={}
same here, remove commented code from PR

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/components/ChatApp/ChatArea.tsx
> +const NameArea = ({ name, credentials }: { name: string, credentials: string }) => {
I think it is more clear if we define a type instead. Something like, 
```
interface NameType {
name: string;
credentials: string
}
```

Then, in NameArea's props, pass `{ name, credentials } : NameType`

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/components/ChatApp/ConversationItem.tsx
> +import { db } from '../../../../backend/firebase/firebase'
Might need to adjust the file structure. Our firebase is currently located in `frontend` folder in the most recent main branch.

2023-04-21 17:02 UTC, DylanTom commented on frontend/src/components/ChatApp/ConversationItem.tsx
> +  console.log(conversation);
Is this `console.log()` necessary?

2023-04-25 01:25 UTC, sriramanved requested changes
please see changes requested

2023-04-25 01:25 UTC, sriramanved commented on frontend/src/styles/globals.css
> +
please remove all of this css and rewrite it using Tailwind

2023-05-02 02:19 UTC, sriramanved commented on frontend/src/assets/chevron_up.tsx
good call, i think these asset imports should be updated to match the way we've been doing it on other tickets @doctakim @p-m-ishra

2023-05-02 02:22 UTC, sriramanved commented on frontend/src/styles/globals.css
> +
could you please resolve @doctakim

2023-05-02 03:54 UTC, hahnandrew commented on frontend/src/components/chatapp/SearchBar.tsx
> +    } catch (err) {
unclear what purpose of err state is

2023-05-02 03:56 UTC, hahnandrew commented on frontend/src/components/chatapp/SearchBar.tsx
> +    } catch (err) {
if for debugging, should remove, if for displaying errors to users, should change code to reflect this in catch block

2023-05-02 04:01 UTC, hahnandrew commented on frontend/src/components/ChatApp/MessageList.tsx
> +      const querySnapShot = await getDocs(queryDoc);
could be good to handle fetching errors so users know whats going on if it happens instead of just having the app crash on them

2023-10-24 20:52 UTC, closed without merging