Popups dashboard
cornellh4i/okb-hope pull request #32
Opened 2023-04-23 19:06 UTC by jessicajcho

pr is a wip. 

## Overview
resolves #29 
Updated patient side dashboard based on updated mid-fi's. 
Created pop-up component for 

## Changes Made

## Test Coverage

## Next Steps (delete if not applicable)

## Related PRs or Issues (delete if not applicable)

## Screenshots (delete if not applicable)

<details>

  <summary>Screen Shot Name</summary>

  

</details>

2023-04-24 19:41 UTC, doctakim requested changes
Great job! There's just a couple of suggestions I added throughout the PR.

2023-04-24 19:41 UTC, biojameskim commented on frontend/src/components/dashboard/AppointmentCard.tsx
> +                      {/* questionnaire answers */}
For the questionnaire answers, since we might have more/less later, it might be good to abstract this out. Could make a separate component for a questionnaire answer and pass a name and question into it since that is the only difference.

Should also probably change the names to be unique

2023-04-24 19:41 UTC, biojameskim commented on frontend/src/components/dashboard/AppointmentList.tsx
I think it might be better to wrap everything in the return with a React Fragment rather than a div.

2023-04-24 19:41 UTC, biojameskim commented on frontend/src/components/dashboard/AppointmentCard.tsx
I think it might be better to wrap everything in the return with a React Fragment rather than a div.

2023-04-24 19:41 UTC, biojameskim commented on frontend/src/components/dashboard/Dashboard.tsx
I think it might be better to wrap everything in the return with a React Fragment rather than a div.

2023-05-02 02:13 UTC, merged

2023-05-02 22:10 UTC, swinshu reviewed
Looks good!